stateDiagram-v2
    [*] --> LedOff

    state LedOff
    note right of LedOff : Entry: LED Low

    state LedOn
    note right of LedOn : Entry: LED High, Trigger ADC

    state HighValueWait
    note right of HighValueWait : Entry: LED Low, wait_ticks = 0

    LedOff --> LedOn : TimerTick

    LedOn --> LedOff : TimerTick
    LedOn --> HighValueWait : AdcResult(val) [val > 70]

    HighValueWait --> LedOff : TimerTick [wait_ticks >= 10 && last_adc <= 70]
    
    HighValueWait --> HighValueWait : TimerTick [wait_ticks++, Trigger ADC]
    HighValueWait --> HighValueWait : AdcResult(val) [Update last_adc]
